[package]
name = "earthmap-surface"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
earthmap-core = { path = "../earthmap-core" }
earthmap-geo = { path = "../earthmap-geo" }
earthmap-minecraft = { path = "../earthmap-minecraft" }
earthmap-region = { path = "../earthmap-region" }
png.workspace = true
quick-xml.workspace = true

[lib]
path = "src/lib.rs"
